# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   build-and-deploy:
    name: devops
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.15]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Artifact
        run: CI='' npm run build

      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: yuanyoung/book-keeping-webdav
          tag: latest
          dockerfile: dockerfile
          registry: docker.io
          username: yuanyoung
          password: ${{ secrets.DOCKER_PSW }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 101.33.125.161
          username: root
          password: ${{ secrets.ALI_PWD }}
          command_timeout: '30m'
          script: |
            cd /root/BookKeeping
            echo '${{ secrets.ALI_PWD }}' | sudo -S bash web-dav.sh